name: "test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: unity-changeset
        with:
          unityVersion: 2021.2.12f1
      - if: steps.unity-changeset.outputs.changeset != '48b1aa000234'
        run: |
          echo '::error changeset value is not correct, ${{ steps.unity-changeset.outputs.changeset }}'
          exit 1

      - uses: ./
        id: unity-changeset2
        continue-on-error: true
        with:
          unityVersion: 2021.2.12f2
      - if: steps.unity-changeset2.outcome == 'success'
        run: |
          echo '::error changeset value is not correct, ${{ steps.unity-changeset2.outputs.changeset }}'
          exit 1